
name: "Lead Collection"
pipelines:
  - slug: "clean_form_entries"
    sources:
      - heroku-form-entry
    destination: bigquery-form-entry
    transformations:
    
      - process_datetimes
      - hasgclid
      - fullname
      - drop_useless
      - combine_duplicates
      - clean_column_categories
      - assign_lead_type
      - phone_country_column
      - correct_location_column
    
