
name: "Lead Collection"
pipelines:
  - slug: "clean_form_entries"
    transformations:
      - process_datetimes
      - has_gclid
      - fullname
      - drop_useless
      - combine_duplicates
      - clean_column_categories
      - assign_lead_type